name: Label new submissions

on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  label-submission:
    runs-on: ubuntu-latest

    steps:
      - name: Check whether this is a submission
        if: contains(github.event.issue.body, '<!-- KIGUBI-SUBMISSION -->')
        run: |
          gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: submission,pending